using System;
using System.IO;
using LinhGioi.Bootstrap;
using LinhGioi.UI;
using LinhGioi.UI.Editor;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

namespace LinhGioi.Foundation.Editor
{
    [InitializeOnLoad]
    public static class M0ProjectGenerator
    {
        private const string GeneratedRoot = "Assets/Game/Generated";
        private const string PipelinePath = GeneratedRoot + "/RenderPipeline/LinhGioiURP.asset";
        private const string RendererDataPath = GeneratedRoot + "/RenderPipeline/LinhGioiUniversalRenderer.asset";
        private const string PanelSettingsPath = GeneratedRoot + "/UI/LinhGioiPanelSettings.asset";
        private const string BootstrapScenePath = GeneratedRoot + "/Scenes/Bootstrap.unity";
        private const string ShowcaseScenePath = GeneratedRoot + "/Scenes/UIShowcase.unity";

        static M0ProjectGenerator()
        {
            EditorApplication.delayCall += EnsureGeneratedFoundation;
        }

        [MenuItem("Tools/Linh Gioi/Rebuild M0 Generated Foundation")]
        public static void RebuildGeneratedFoundation()
        {
            DeleteDisposableGeneratedFoundation();
            AssetDatabase.Refresh();
            EnsureGeneratedFoundation();
        }

        private static void DeleteDisposableGeneratedFoundation()
        {
            // Only scene/UI/render-pipeline assets are disposable outputs owned by
            // this editor generator. Protocol C# files are generated separately under
            // Assets/Game/Protocol/Generated by tools/prepare_unity_protocol.py.
            DeleteIfExists(GeneratedRoot + "/RenderPipeline");
            DeleteIfExists(GeneratedRoot + "/Scenes");
            DeleteIfExists(GeneratedRoot + "/UI");
        }

        private static void DeleteIfExists(string path)
        {
            if (AssetDatabase.IsValidFolder(path) || File.Exists(path)) AssetDatabase.DeleteAsset(path);
        }

        public static void EnsureGeneratedFoundation()
        {
            try
            {
                var theme = ThemeTokenImporter.EnsureTheme();
                var pipeline = EnsureUrp();
                EnsureBootstrapScene();
                EnsureShowcaseScene(theme);
                GraphicsSettings.defaultRenderPipeline = pipeline;
                QualitySettings.renderPipeline = pipeline;
                EnsureBuildSettings();
                AssetDatabase.SaveAssets();
                Debug.Log("[LinhGioi] M0 generated Unity foundation is ready.");
            }
            catch (Exception exception)
            {
                Debug.LogException(exception);
            }
        }

        private static UniversalRenderPipelineAsset EnsureUrp()
        {
            EnsureFolder(GeneratedRoot + "/RenderPipeline");
            var asset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(PipelinePath);
            if (asset == null)
            {
                asset = UniversalRenderPipelineAsset.Create();
                asset.renderScale = 1.0f;
                AssetDatabase.CreateAsset(asset, PipelinePath);
            }

            EnsureUrpDefaultRenderer(asset);
            return asset;
        }

        private static void EnsureUrpDefaultRenderer(UniversalRenderPipelineAsset asset)
        {
            var rendererData = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererDataPath);
            if (rendererData == null)
            {
                rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
                rendererData.name = "LinhGioiUniversalRenderer";
                AssetDatabase.CreateAsset(rendererData, RendererDataPath);
            }

            var serializedAsset = new SerializedObject(asset);
            var rendererDataList = serializedAsset.FindProperty("m_RendererDataList");
            if (rendererDataList == null)
                throw new InvalidOperationException("Unable to configure URP default renderer: m_RendererDataList not found.");

            if (rendererDataList.arraySize == 0) rendererDataList.arraySize = 1;
            rendererDataList.GetArrayElementAtIndex(0).objectReferenceValue = rendererData;

            var defaultRendererIndex = serializedAsset.FindProperty("m_DefaultRendererIndex");
            if (defaultRendererIndex != null) defaultRendererIndex.intValue = 0;

            serializedAsset.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(asset);
            EditorUtility.SetDirty(rendererData);
        }

        private static void EnsureBootstrapScene()
        {
            if (File.Exists(BootstrapScenePath)) return;
            EnsureFolder(GeneratedRoot + "/Scenes");
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var root = new GameObject("GameBootstrap");
            root.AddComponent<GameBootstrap>();
            EditorSceneManager.SaveScene(scene, BootstrapScenePath);
        }

        private static void EnsureShowcaseScene(ThemeTokens theme)
        {
            if (File.Exists(ShowcaseScenePath)) return;
            EnsureFolder(GeneratedRoot + "/Scenes");
            EnsureFolder(GeneratedRoot + "/UI");
            var panelSettings = AssetDatabase.LoadAssetAtPath<PanelSettings>(PanelSettingsPath);
            if (panelSettings == null)
            {
                panelSettings = ScriptableObject.CreateInstance<PanelSettings>();
                AssetDatabase.CreateAsset(panelSettings, PanelSettingsPath);
            }

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var root = new GameObject("UIShowcase");
            var document = root.AddComponent<UIDocument>();
            document.panelSettings = panelSettings;
            var showcase = root.AddComponent<UIShowcaseController>();
            showcase.Configure(theme);
            EditorSceneManager.SaveScene(scene, ShowcaseScenePath);
        }

        private static void EnsureBuildSettings()
        {
            EditorBuildSettings.scenes = new[] { new EditorBuildSettingsScene(BootstrapScenePath, true) };
        }

        private static void EnsureFolder(string path)
        {
            var parts = path.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }
    }
}
